apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::121202887497:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::121202887497:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-F0Q5K10742SP
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-11T11:52:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1393"
  uid: ae26fd25-4864-4107-bb19-e493a130b1e2
